/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'cv' : [] | [Document],
  'id' : bigint,
  'qualificationCert' : [] | [Document],
  'yearsExperience' : bigint,
  'fullName' : string,
  'matricCert' : [] | [Document],
  'tradeSkill' : string,
  'email' : string,
  'physicalAddress' : string,
  'idNumber' : string,
  'timestamp' : bigint,
  'idCopy' : [] | [Document],
  'phoneNumber' : string,
  'workAreas' : string,
}
export interface CandidateInput {
  'yearsExperience' : bigint,
  'fullName' : string,
  'tradeSkill' : string,
  'email' : string,
  'physicalAddress' : string,
  'idNumber' : string,
  'phoneNumber' : string,
  'workAreas' : string,
}
export interface ContactInput {
  'contactType' : { 'client' : null } |
    { 'candidate' : null },
  'fullName' : string,
  'email' : string,
  'message' : string,
  'phoneNumber' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'contactType' : { 'client' : null } |
    { 'candidate' : null },
  'fullName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phoneNumber' : string,
}
export interface Document {
  'blob' : ExternalBlob,
  'fileName' : string,
  'fileType' : string,
}
export interface Enquiry {
  'id' : bigint,
  'serviceType' : string,
  'fullName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'companyName' : [] | [string],
  'phoneNumber' : string,
  'location' : string,
}
export interface EnquiryInput {
  'serviceType' : string,
  'fullName' : string,
  'email' : string,
  'message' : string,
  'companyName' : [] | [string],
  'phoneNumber' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  'deleteContactMessage' : ActorMethod<[bigint], undefined>,
  'deleteEnquiry' : ActorMethod<[bigint], undefined>,
  'getAllCandidates' : ActorMethod<[], Array<Candidate>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidatesByTrade' : ActorMethod<[string], Array<Candidate>>,
  'getPublicContactInfo' : ActorMethod<
    [],
    {
      'areas' : Array<string>,
      'whatsapp' : string,
      'email' : string,
      'facebook' : string,
      'phone' : string,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCandidate' : ActorMethod<[CandidateInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[ContactInput], bigint>,
  'submitEnquiry' : ActorMethod<[EnquiryInput], bigint>,
  'updateCandidate' : ActorMethod<[bigint, CandidateInput], undefined>,
  'uploadCandidateDocument' : ActorMethod<
    [bigint, string, string, ExternalBlob, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];