/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
  'fileType' : IDL.Text,
});
export const Candidate = IDL.Record({
  'cv' : IDL.Opt(Document),
  'id' : IDL.Nat,
  'qualificationCert' : IDL.Opt(Document),
  'yearsExperience' : IDL.Nat,
  'fullName' : IDL.Text,
  'matricCert' : IDL.Opt(Document),
  'tradeSkill' : IDL.Text,
  'email' : IDL.Text,
  'physicalAddress' : IDL.Text,
  'idNumber' : IDL.Text,
  'timestamp' : IDL.Int,
  'idCopy' : IDL.Opt(Document),
  'phoneNumber' : IDL.Text,
  'workAreas' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'contactType' : IDL.Variant({ 'client' : IDL.Null, 'candidate' : IDL.Null }),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CandidateInput = IDL.Record({
  'yearsExperience' : IDL.Nat,
  'fullName' : IDL.Text,
  'tradeSkill' : IDL.Text,
  'email' : IDL.Text,
  'physicalAddress' : IDL.Text,
  'idNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'workAreas' : IDL.Text,
});
export const ContactInput = IDL.Record({
  'contactType' : IDL.Variant({ 'client' : IDL.Null, 'candidate' : IDL.Null }),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const EnquiryInput = IDL.Record({
  'serviceType' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'companyName' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteEnquiry' : IDL.Func([IDL.Nat], [], []),
  'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidatesByTrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Candidate)],
      ['query'],
    ),
  'getPublicContactInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'areas' : IDL.Vec(IDL.Text),
          'whatsapp' : IDL.Text,
          'email' : IDL.Text,
          'facebook' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCandidate' : IDL.Func([CandidateInput], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([ContactInput], [IDL.Nat], []),
  'submitEnquiry' : IDL.Func([EnquiryInput], [IDL.Nat], []),
  'updateCandidate' : IDL.Func([IDL.Nat, CandidateInput], [], []),
  'uploadCandidateDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
  });
  const Candidate = IDL.Record({
    'cv' : IDL.Opt(Document),
    'id' : IDL.Nat,
    'qualificationCert' : IDL.Opt(Document),
    'yearsExperience' : IDL.Nat,
    'fullName' : IDL.Text,
    'matricCert' : IDL.Opt(Document),
    'tradeSkill' : IDL.Text,
    'email' : IDL.Text,
    'physicalAddress' : IDL.Text,
    'idNumber' : IDL.Text,
    'timestamp' : IDL.Int,
    'idCopy' : IDL.Opt(Document),
    'phoneNumber' : IDL.Text,
    'workAreas' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'contactType' : IDL.Variant({
      'client' : IDL.Null,
      'candidate' : IDL.Null,
    }),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CandidateInput = IDL.Record({
    'yearsExperience' : IDL.Nat,
    'fullName' : IDL.Text,
    'tradeSkill' : IDL.Text,
    'email' : IDL.Text,
    'physicalAddress' : IDL.Text,
    'idNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'workAreas' : IDL.Text,
  });
  const ContactInput = IDL.Record({
    'contactType' : IDL.Variant({
      'client' : IDL.Null,
      'candidate' : IDL.Null,
    }),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const EnquiryInput = IDL.Record({
    'serviceType' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'companyName' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteEnquiry' : IDL.Func([IDL.Nat], [], []),
    'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidatesByTrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Candidate)],
        ['query'],
      ),
    'getPublicContactInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'areas' : IDL.Vec(IDL.Text),
            'whatsapp' : IDL.Text,
            'email' : IDL.Text,
            'facebook' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCandidate' : IDL.Func([CandidateInput], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([ContactInput], [IDL.Nat], []),
    'submitEnquiry' : IDL.Func([EnquiryInput], [IDL.Nat], []),
    'updateCandidate' : IDL.Func([IDL.Nat, CandidateInput], [], []),
    'uploadCandidateDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };