/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactInput {
    contactType: Variant_client_candidate;
    fullName: string;
    email: string;
    message: string;
    phoneNumber: string;
}
export interface CandidateInput {
    yearsExperience: bigint;
    fullName: string;
    tradeSkill: string;
    email: string;
    physicalAddress: string;
    idNumber: string;
    phoneNumber: string;
    workAreas: string;
}
export interface EnquiryInput {
    serviceType: string;
    fullName: string;
    email: string;
    message: string;
    companyName?: string;
    phoneNumber: string;
    location: string;
}
export interface ContactMessage {
    id: bigint;
    contactType: Variant_client_candidate;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phoneNumber: string;
}
export interface Candidate {
    cv?: Document;
    id: bigint;
    qualificationCert?: Document;
    yearsExperience: bigint;
    fullName: string;
    matricCert?: Document;
    tradeSkill: string;
    email: string;
    physicalAddress: string;
    idNumber: string;
    timestamp: bigint;
    idCopy?: Document;
    phoneNumber: string;
    workAreas: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    blob: ExternalBlob;
    fileName: string;
    fileType: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Enquiry {
    id: bigint;
    serviceType: string;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    companyName?: string;
    phoneNumber: string;
    location: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_client_candidate {
    client = "client",
    candidate = "candidate"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCandidate(id: bigint): Promise<void>;
    deleteContactMessage(id: bigint): Promise<void>;
    deleteEnquiry(id: bigint): Promise<void>;
    getAllCandidates(): Promise<Array<Candidate>>;
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidatesByTrade(trade: string): Promise<Array<Candidate>>;
    getPublicContactInfo(): Promise<{
        areas: Array<string>;
        whatsapp: string;
        email: string;
        facebook: string;
        phone: string;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerCandidate(input: CandidateInput): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactMessage(input: ContactInput): Promise<bigint>;
    submitEnquiry(input: EnquiryInput): Promise<bigint>;
    updateCandidate(id: bigint, input: CandidateInput): Promise<void>;
    uploadCandidateDocument(candidateId: bigint, fileName: string, fileType: string, blob: ExternalBlob, docType: string): Promise<void>;
}
import type { Candidate as _Candidate, ContactInput as _ContactInput, ContactMessage as _ContactMessage, Document as _Document, Enquiry as _Enquiry, EnquiryInput as _EnquiryInput, ExternalBlob as _ExternalBlob, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCandidate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCandidate(arg0);
            return result;
        }
    }
    async deleteContactMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessage(arg0);
            return result;
        }
    }
    async deleteEnquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEnquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEnquiry(arg0);
            return result;
        }
    }
    async getAllCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCandidates();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCandidates();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidatesByTrade(arg0: string): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidatesByTrade(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidatesByTrade(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicContactInfo(): Promise<{
        areas: Array<string>;
        whatsapp: string;
        email: string;
        facebook: string;
        phone: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicContactInfo();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerCandidate(arg0: CandidateInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCandidate(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContactMessage(arg0: ContactInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(to_candid_ContactInput_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(to_candid_ContactInput_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitEnquiry(arg0: EnquiryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(to_candid_EnquiryInput_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(to_candid_EnquiryInput_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCandidate(arg0: bigint, arg1: CandidateInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(arg0, arg1);
            return result;
        }
    }
    async uploadCandidateDocument(arg0: bigint, arg1: string, arg2: string, arg3: ExternalBlob, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCandidateDocument(arg0, arg1, arg2, await to_candid_ExternalBlob_n33(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCandidateDocument(arg0, arg1, arg2, await to_candid_ExternalBlob_n33(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
async function from_candid_Candidate_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Promise<Candidate> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ContactMessage_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactMessage): ContactMessage {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Enquiry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Promise<Document | null> {
    return value.length === 0 ? null : await from_candid_Document_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cv: [] | [_Document];
    id: bigint;
    qualificationCert: [] | [_Document];
    yearsExperience: bigint;
    fullName: string;
    matricCert: [] | [_Document];
    tradeSkill: string;
    email: string;
    physicalAddress: string;
    idNumber: string;
    timestamp: bigint;
    idCopy: [] | [_Document];
    phoneNumber: string;
    workAreas: string;
}): Promise<{
    cv?: Document;
    id: bigint;
    qualificationCert?: Document;
    yearsExperience: bigint;
    fullName: string;
    matricCert?: Document;
    tradeSkill: string;
    email: string;
    physicalAddress: string;
    idNumber: string;
    timestamp: bigint;
    idCopy?: Document;
    phoneNumber: string;
    workAreas: string;
}> {
    return {
        cv: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.cv)),
        id: value.id,
        qualificationCert: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.qualificationCert)),
        yearsExperience: value.yearsExperience,
        fullName: value.fullName,
        matricCert: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.matricCert)),
        tradeSkill: value.tradeSkill,
        email: value.email,
        physicalAddress: value.physicalAddress,
        idNumber: value.idNumber,
        timestamp: value.timestamp,
        idCopy: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.idCopy)),
        phoneNumber: value.phoneNumber,
        workAreas: value.workAreas
    };
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    fileName: string;
    fileType: string;
}): Promise<{
    blob: ExternalBlob;
    fileName: string;
    fileType: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName,
        fileType: value.fileType
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactType: {
        client: null;
    } | {
        candidate: null;
    };
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phoneNumber: string;
}): {
    id: bigint;
    contactType: Variant_client_candidate;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phoneNumber: string;
} {
    return {
        id: value.id,
        contactType: from_candid_variant_n20(_uploadFile, _downloadFile, value.contactType),
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    serviceType: string;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    companyName: [] | [string];
    phoneNumber: string;
    location: string;
}): {
    id: bigint;
    serviceType: string;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    companyName?: string;
    phoneNumber: string;
    location: string;
} {
    return {
        id: value.id,
        serviceType: value.serviceType,
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        companyName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.companyName)),
        phoneNumber: value.phoneNumber,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    candidate: null;
}): Variant_client_candidate {
    return "client" in value ? Variant_client_candidate.client : "candidate" in value ? Variant_client_candidate.candidate : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Promise<Array<Candidate>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Candidate_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactMessage>): Array<ContactMessage> {
    return value.map((x)=>from_candid_ContactMessage_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n22(_uploadFile, _downloadFile, x));
}
function to_candid_ContactInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInput): _ContactInput {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_EnquiryInput_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryInput): _EnquiryInput {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactType: Variant_client_candidate;
    fullName: string;
    email: string;
    message: string;
    phoneNumber: string;
}): {
    contactType: {
        client: null;
    } | {
        candidate: null;
    };
    fullName: string;
    email: string;
    message: string;
    phoneNumber: string;
} {
    return {
        contactType: to_candid_variant_n30(_uploadFile, _downloadFile, value.contactType),
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    fullName: string;
    email: string;
    message: string;
    companyName?: string;
    phoneNumber: string;
    location: string;
}): {
    serviceType: string;
    fullName: string;
    email: string;
    message: string;
    companyName: [] | [string];
    phoneNumber: string;
    location: string;
} {
    return {
        serviceType: value.serviceType,
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        companyName: value.companyName ? candid_some(value.companyName) : candid_none(),
        phoneNumber: value.phoneNumber,
        location: value.location
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_client_candidate): {
    client: null;
} | {
    candidate: null;
} {
    return value == Variant_client_candidate.client ? {
        client: null
    } : value == Variant_client_candidate.candidate ? {
        candidate: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
